server:
  port: 8080

datasource:
  names: test2
  default:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.175.35:3306/test1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Zfy@55665566
  test2:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.175.35:3306/test2?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Zfy@55665566
